spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redisDemo?characterEncoding=utf8
    username: root
    password: linli1206
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    password:
    database: 0
#自定义属性值
app:
  name: CacheDemo

#缓存常量定义
User: #类名
  library: users #库名
  keyPrefix: user #键值前缀